### ISSUE TITLE
代码运行问题

### ISSUE THREAD

**Issue by AutoMachine0** [AutoML-Research/PAS#1]
PAS是一个非常棒工作，我想尝试运行代码，遇到以下问题，希望作者能够提供相关帮助，十分感谢

运行问题1：Step1中 需要输出epochs参数，但在train_search.py脚本中没有epochs参数的配置项.
运行问题2：脚本：agg_zoo.py中，类GAT_mix 没有对应的 lin_l 属性导致程序运行报错.报错信息如下:
![lin_l](https://user-images.githubusercontent.com/89678479/158627329-89ac09c3-e25e-4c3d-8e7c-63880ae1e0a0.png)

**Comment by wei-ln** [comment]
感谢您的关注，上述问题的解答如下：

1. train_search.py中epochs 请参考args.epochs这一项的使用说明
2. GAT_mix这个类复用了pyg中提供的GATConv，当前代码是基于pyg 1.7.2的版本。 在pyg2.0的更新中对GATConv的实现做了更改，所以会报错。如果您想运行这份代码，可以使用使用pyg1.7.2的版本，或者参考https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/nn/conv/gat_conv.py#L180 来修改GAT_mix的forward函数即可使用。
