### ISSUE TITLE
代码运行中断

### ISSUE THREAD

**Issue by liutingqin** [AutoML-Research/PAS#2]
在运行train_search文件时，有时候会中断报错RuntimeError:operation does not have an identity.报错上一句为size = int(batch.max().item() + 1) if size is None else size，提示是torch-geometric包的问题.
配置环境与博主github所给的环境一致

**Comment by nddd1** [comment]
提示没有self.lin_l这个函数，位置在agg_zoo.py-class GAT_mix()内，这是为什么？

**Comment by wei-ln** [comment]
> 在运行train_search文件时，有时候会中断报错RuntimeError:operation does not have an identity.报错上一句为size = int(batch.max().item() + 1) if size is None else size，提示是torch-geometric包的问题.
> 配置环境与博主github所给的环境一致

感谢关注～ 我这边偶尔也会有这个问题，目前尚未查清 ：(

**Comment by wei-ln** [comment]
> 提示没有self.lin_l这个函数，位置在agg_zoo.py-class GAT_mix()内，这是为什么？

感谢关注，应该是版本不同导致的。

GAT_mix这个类复用了pyg中提供的GATConv，当前代码是基于pyg 1.7.2的版本。 在pyg2.0的更新中对GATConv的实现做了更改，所以会报错。如果您想运行这份代码，可以使用使用pyg1.7.2的版本，或者参考https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/nn/conv/gat_conv.py#L180 来修改GAT_mix的forward函数即可使用。
